// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hmtqbtbxpyljgucpdoxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhtdHFidGJ4cHlsamd1Y3Bkb3hiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMjA5NTgsImV4cCI6MjA3MjU5Njk1OH0.aDKRuomq9tjMeUFIq1oSFtFbKu-iufz3hFwpx293vgM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
